#!/bin/bash

echo "Pretending to build an rpm"
echo "Pretending to build an rpm"
echo "Pretending to build an rpm"
echo "Pretending to build an rpm"
echo "Pretending to build an rpm"
echo "Pretending to build an rpm"
echo "Pretending to build an rpm"
echo "Pretending to build an rpm"
echo "Pretending to build an rpm"
echo
